#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: admin
    password: admin
  filter:
    create: All tasks


camunda:
  bpm:
    database:
      schema-update: 'true'
      schema-name: test
      table-prefix: test.



spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

#  database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    username: demo
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    password: demo123

#    *******MySql Data Base *******
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test
    password: root
#    oracle  Data Base config



#   *********** h2 Data Data Base config*******
#    driver-class-name: org.h2.Driver
#    username: sa
#    url: jdbc:h2:file:~/demo
#    password: ''
#  h2:
#    console:
#      enabled: 'true'
#      path: /h2




